### ISSUE TITLE
SMAC class name in latest version

### ISSUE THREAD

**Issue by ndangtt** [automl/ParameterImportance#112]
Hello,

I saw that current PIMP source code has the same issue as mentioned [here](https://github.com/automl/SMAC3/issues/527), and thought that I should mention that to you! 

These are the line with the issue: 
https://github.com/automl/ParameterImportance/blob/45e776f987147368cefba86bc685d949a2938060/pimp/pimp.py#L15
https://github.com/automl/ParameterImportance/blob/45e776f987147368cefba86bc685d949a2938060/pimp/pimp.py#L34

Best regards,
Nguyen

**Comment by AndreBiedenkapp** [comment]
Oh thank you very much for reporting the issue.
That was unfortunately overlooked.

**Comment by ndangtt** [comment]
You're very welcome! Thank you for looking at it so quickly! :)

Nguyen

**Comment by shukon** [comment]
Sorry, lost this in my stack. Fixed in #113 and will be released asap.
