### ISSUE TITLE
Update RF-Interface to newest SMAC version

### ISSUE THREAD

**Issue by mlindauer** [automl/ParameterImportance#15]
File "/home/lindauer/git/ParameterImportance/pimp/epm/unlogged_rf_with_instances.py", line 62, in __init__
    eps_purity=eps_purity, max_num_nodes=max_num_nodes, seed=seed)
TypeError: __init__() missing 1 required positional argument: 'bounds'

**Comment by AndreBiedenkapp** [comment]
Fixed in latest pull request
