### ISSUE TITLE
Always import standard package before own package

### ISSUE THREAD

**Issue by mlindauer** [automl/ParameterImportance#3]
It is a better style and it avoids some troubles,
if you always first import standard packages,
then your own third party packages
and then your own project packages.
E.g.

```
import sys

import smac

import importance
```

I fixed this in `importance.importance`.

btw: the package should not be called importance because it is ambiguous.

**Comment by sfalkner** [comment]
If only everyone read PEP8 :)

**Comment by mlindauer** [comment]
@sfalkner and you have time to read these issues here? I'm shocked ;-)
