### ISSUE TITLE
PIMP / fANOVA / Integer Parameter does not seem to work well

### ISSUE THREAD

**Issue by janvanrijn** [automl/ParameterImportance#32]
All integer parameter plots are 'constant'. I can give a MWE later. If I directly run through fANOVA it works correctly.

**Comment by Krxsy** [comment]
Ok, I think I found out why (hypercube is not taken into account). I'll fix it today :-)

**Comment by Krxsy** [comment]
It should work now. Let me know if it still happens.

**Comment by KEggensperger** [comment]
Hi, unfortunately I think this is not yet fixed. I used the following command to produce fanova results resulting in empty plots for some hyperparameters. 

python <path/to/pimp/repo>/ParameterImportance/scripts/evaluate.py -S scenario.txt -M fanova -H "*/runhistory.json"

I would guess that integer hyperparameters on log scale and categorical hyperparameters with strings ["1", "2", "3", etc] are still a problem.

The plots and data to reproduce this is here:
[probsat-7sat90_pimped.tar.gz](https://github.com/automl/ParameterImportance/files/1242163/probsat-7sat90_pimped.tar.gz)

**Comment by AndreBiedenkapp** [comment]
@Krxsy I just tested everything with the latest fANOVA and this problem still exists.
I was just checking in to see which issues I can/have to work on

**Comment by Krxsy** [comment]
Both issues are fixed and it should work now.
