### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'rs'

### ISSUE THREAD

**Issue by shukon** [automl/ParameterImportance#36]
Currently, running any example results in `TypeError: __init__() got an unexpected keyword argument 'rs'`, which is related to the initialization of the `RFRImputator`, which takes a random number generator the argument `rng`, not `rs` since [this commit.](https://github.com/automl/SMAC3/commit/7e7a2d31c1761e38fd0432058d00559e2f8aeded#diff-162eef16cd499c942a62ad9341770ad7L23)

**Comment by AndreBiedenkapp** [comment]
I guess this is the case for smac 0.6.
I'll make a quick pass and see that i'll support the newest smac version

**Comment by AndreBiedenkapp** [comment]
This should be fixed now.
Now PIMP requires the latest SMAC version to work (which you seem to have anyways)
I'll not update the master branch just yet. If you find any more errors feel free to report them or create a pull request.

Thanks again for mentioning that.
