### ISSUE TITLE
Clip std

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/ParameterImportance#39]
In runtime scenarios it can be the case that the std shows that the algorithm might result in negative runtimes. The std should be clipped such that the result is never smaller than 0 in these cases

**Comment by sfalkner** [comment]
I'm not sure what you do with the std, but clipping it would artificially reduce the uncertainty, wouldn't it?
If you sample from that distribution, you could simply reject samples that are negative. Have you looked at the distribution of values? It should be pretty non-gaussian you encounter that the std >= mean if all your values are positive.

**Comment by AndreBiedenkapp** [comment]
I should have mentioned that it is just for plotting purposes. Otherwise it might give users the wrong impression of the results.
To clarify: I want to set the lower bound for the ablation plots to 0.

**Comment by AndreBiedenkapp** [comment]
Fixed in #40
