### ISSUE TITLE
Newest version of ConfigSpace

### ISSUE THREAD

**Issue by shukon** [automl/ParameterImportance#43]
@AndreBiedenkapp I think there is an import error with ConfigSpace >= 0.4.x:
This makes it hard to work with the newest version of SMAC, since it requires the newest ConfigSpace-version.

```
from pimp.importance.importance import Importance
  File "/home/shuki/virtenv/vespy/lib/python3.5/site-packages/pimp/importance/importance.py", line 16, in <module>
from pimp.configspace import CategoricalHyperparameter, Configuration, \
  File "/home/shuki/virtenv/vespy/lib/python3.5/site-packages/pimp/configspace/__init__.py", line 2, in <module>
from ConfigSpace.io import pcs
ImportError: No module named 'ConfigSpace.io' ```

**Comment by AndreBiedenkapp** [comment]
@shukon Thanks for highlighting that issue. However the latest pypi release requires ConfigSpace < 0.4 [see.](https://github.com/automl/SMAC3/blob/7a0014cf2e3661b5facbe6432886316187148f49/requirements.txt#L7)

Changing the CS version not only affects PIMP but also fANOVA.
I forked fANOVA to quickly address the small issues that arise from that problem.
I'll update the development branch accordingly

**Comment by shukon** [comment]
Oh, I guess I got confused with the versions regarding the pypi release. Thanks a lot, though!
