### ISSUE TITLE
feature array is modified by PCA in forward selection

### ISSUE THREAD

**Issue by shukon** [automl/ParameterImportance#44]
Hi,
not sure if intended: [in forward_selection](https://github.com/automl/ParameterImportance/blob/466918ac7ddb8631ba4d3a778d55155db4c7a36f/pimp/evaluator/forward_selection.py#L67) the `self.scenario.feature_array` is directly replaced by the PCA'ed array. Later use of the same scenario is difficult when the reference itself is modified.
Personally I'd assume that the original scenario-object is not changed when I pass it to an evaluator. I now perform a deepcopy before passing, but this might be difficult to discover when using the package without being aware of it?

**Comment by AndreBiedenkapp** [comment]
Thanks. I'll change that!
