### ISSUE TITLE
fANOVA results

### ISSUE THREAD

**Issue by mlindauer** [automl/ParameterImportance#45]
Using SpySMAC to obtain fANOVA results for spear-swv, the tables look like that:

sp-var-dec-heur | 0.967491
sp-var-dec-heur & sp-res-order-heur | 0.974664
sp-var-dec-heur & sp-rand-var-dec-scaling | 0.972481
sp-var-dec-heur & sp-rand-var-dec-freq | 0.969324
sp-var-dec-heur & sp-learned-clause-sort-heur | 0.968437

That's weird because the scores should sum up to 1. Please check.

**Comment by sfalkner** [comment]
One problem here is that fANOVA computes both
- the importance of a pair of parameters alone
- and the importance of the pair plus the single contributions
You probably take the first, where only if you take the latter the sum should be less or equal to one (the sum of all possible parameter combinations will sum to one...)

**Comment by mlindauer** [comment]
I would prefer the latter which also corresponds to the output of the Java implementation.

@AndreBiedenkapp 
On which end, do we need to change this? PIMP package? fANOVA package?  SpySMAC package?

**Comment by AndreBiedenkapp** [comment]
I'm a bit confused here.
In my PIMP implementation, I access the fANOVA values, titled 'total importance'. This should be 
> the importance of the pair plus the single contributions
as Stefan wrote.

Further in the fANOVA code 'total importance' is also what is used when calling 
[get_most_important_pairwise_marginals](https://github.com/automl/fanova/blob/fbb0c65c7a8270cb2b1919cccee72cf8b2813e44/fanova/fanova.py#L348-L393) (line 381).

So I'd have to guess that something is up in fANOVA.

**Comment by Krxsy** [comment]
Now it is ensured that it is always lesser or equal to one when calling the most important pairwise marginals.

**Comment by shukon** [comment]
Assuming this to be resolved. Feel free to reopen.
