### ISSUE TITLE
Save results as json in importance

### ISSUE THREAD

**Issue by shukon** [automl/ParameterImportance#67]
Similarily to [postevaluation printing of comparison table](https://github.com/automl/ParameterImportance/blob/89521a586d4b12269097d57b4edf212dea22f981/pimp/importance/importance.py#L506) in `.tex`-format, it would be nice to postevaluation save a machine-readable format like `.json` in the `Importance`-object that saves a combined json for all evaluators even if they are [not run](https://github.com/automl/ParameterImportance/blob/89521a586d4b12269097d57b4edf212dea22f981/pimp/pimp.py#L157-L158) with the `all`-option via the `pimp`-object, but independently.

**Comment by AndreBiedenkapp** [comment]
a json file called pimp_results.json will be created in the user specified output folder.
The fANOVA, ablation and LPI values in the json file are between [0, 1]. If someone wants them as percentages, they need to be multiplied by 100
